<?php

/**
 * @file
 * Contains miscellaneous File Checker code.
 */

/**
 * Implements hook_cron().
 */
function file_checker_cron() {
  if (\Drupal::config('file_checker.settings')->get('run_by_cron')) {
    $frequency_limit = \Drupal::config('file_checker.settings')->get('frequency_limit');
    $last_run_start = \Drupal::state()->get('file_checker.last_run_start');
    $next_run = $last_run_start + $frequency_limit;
    if (REQUEST_TIME > $next_run) {
      \Drupal::service('file_checker.file_checker')->queueFiles();
    }
  }
}
